module.exports = {
  MAX_CLAUDE_CALLS_PRO_SCAN: 10,
  MAX_ARTIKEL_ALTER_TAGE: 7,
  MIN_RELEVANZ_SCORE: 7,
  REQUEST_TIMEOUT_MS: 10000,
  RETRY_VERSUCHE: 3,
  RETRY_PAUSE_MS: 5000,
  PAUSE_ZWISCHEN_QUELLEN_MS: 2000,
  MAX_FEHLER_PRO_QUELLE: 3,
  VOLLTEXT_MAX_ZEICHEN: 500,
  TAGES_BUDGET_USD: 1.00,
}
